
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'COLON DASH DEDENT INDENT KEY NEWLINE SERVICES VALUEdocument : element_list\n                | emptyelement_list : element\n                    | element_list elementelement : key_or_services COLON VALUE NEWLINE\n               | key_or_services COLON NEWLINE\n               | key_or_services COLON NEWLINE INDENT block DEDENTkey_or_services : KEY\n                       | SERVICESblock : block_item\n             | block block_itemblock_item : KEY COLON VALUE NEWLINE\n                  | KEY COLON NEWLINE\n                  | KEY COLON NEWLINE INDENT block DEDENT\n                  | list_itemslist_items : list_item\n                  | list_items list_itemlist_item : DASH VALUE NEWLINEempty :'
    
_lr_action_items = {'$end':([0,1,2,3,4,8,11,12,20,],[-19,0,-1,-2,-3,-4,-6,-5,-7,]),'KEY':([0,2,4,8,11,12,13,14,15,17,18,20,21,23,26,27,28,29,30,31,],[6,6,-3,-4,-6,-5,16,16,-10,-15,-16,-7,-11,-17,-13,-18,-12,16,16,-14,]),'SERVICES':([0,2,4,8,11,12,20,],[7,7,-3,-4,-6,-5,-7,]),'COLON':([5,6,7,16,],[9,-8,-9,22,]),'VALUE':([9,19,22,],[10,24,25,]),'NEWLINE':([9,10,22,24,25,],[11,12,26,27,28,]),'INDENT':([11,26,],[13,29,]),'DASH':([13,14,15,17,18,21,23,26,27,28,29,30,31,],[19,19,-10,19,-16,-11,-17,-13,-18,-12,19,19,-14,]),'DEDENT':([14,15,17,18,21,23,26,27,28,30,31,],[20,-10,-15,-16,-11,-17,-13,-18,-12,31,-14,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'document':([0,],[1,]),'element_list':([0,],[2,]),'empty':([0,],[3,]),'element':([0,2,],[4,8,]),'key_or_services':([0,2,],[5,5,]),'block':([13,29,],[14,30,]),'block_item':([13,14,29,30,],[15,21,15,21,]),'list_items':([13,14,29,30,],[17,17,17,17,]),'list_item':([13,14,17,29,30,],[18,18,23,18,18,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> document","S'",1,None,None,None),
  ('document -> element_list','document',1,'p_document','parser.py',6),
  ('document -> empty','document',1,'p_document','parser.py',7),
  ('element_list -> element','element_list',1,'p_element_list','parser.py',11),
  ('element_list -> element_list element','element_list',2,'p_element_list','parser.py',12),
  ('element -> key_or_services COLON VALUE NEWLINE','element',4,'p_element','parser.py',21),
  ('element -> key_or_services COLON NEWLINE','element',3,'p_element','parser.py',22),
  ('element -> key_or_services COLON NEWLINE INDENT block DEDENT','element',6,'p_element','parser.py',23),
  ('key_or_services -> KEY','key_or_services',1,'p_key_or_services','parser.py',32),
  ('key_or_services -> SERVICES','key_or_services',1,'p_key_or_services','parser.py',33),
  ('block -> block_item','block',1,'p_block','parser.py',38),
  ('block -> block block_item','block',2,'p_block','parser.py',39),
  ('block_item -> KEY COLON VALUE NEWLINE','block_item',4,'p_block_item','parser.py',51),
  ('block_item -> KEY COLON NEWLINE','block_item',3,'p_block_item','parser.py',52),
  ('block_item -> KEY COLON NEWLINE INDENT block DEDENT','block_item',6,'p_block_item','parser.py',53),
  ('block_item -> list_items','block_item',1,'p_block_item','parser.py',54),
  ('list_items -> list_item','list_items',1,'p_list_items','parser.py',66),
  ('list_items -> list_items list_item','list_items',2,'p_list_items','parser.py',67),
  ('list_item -> DASH VALUE NEWLINE','list_item',3,'p_list_item','parser.py',74),
  ('empty -> <empty>','empty',0,'p_empty','parser.py',78),
]
